### ISSUE TITLE
Constantinople Progress Tracker

### ISSUE THREAD

**Issue by Souptacular** [ethereum/pm#53] opened 2018-07-30 19:38 UTC
This issue is meant to track the progress of client implementation and tests of the EIPs for the upcoming Constantinople hard fork.

Migrated to https://github.com/ethereum/pm/wiki/Constantinople-Progress-Tracker

## [Test Cases Spreadsheet](https://docs.google.com/spreadsheets/d/1xat7UI8GtB4ZGVdlK5_XQSHJZaMThi4SrlcL8XMZb5Q/edit#gid=1811198384)

**Comment by carver** [comment] 2018-07-30 20:34
Trinity Constantinople Milestone: https://github.com/ethereum/py-evm/milestone/2

**Comment by 5chdn** [comment] 2018-07-31 07:41
Parity Ethereum: 
- EIP-1052 :white_check_mark: Yes https://github.com/paritytech/parity-ethereum/pull/9234
- EIP-1087 :exclamation:  needs discussion https://github.com/paritytech/parity-ethereum/issues/8427#issuecomment-408782377

**Comment by jbaylina** [comment] 2018-07-31 10:07
Is EIP-1108 and EIP-1109 going to be included in Constantinople ?

**Comment by ayrat555** [comment] 2018-08-01 09:56
Mana progress: https://github.com/poanetwork/mana/issues/307

**Comment by pipermerriam** [comment] 2018-08-01 17:05
Trinity

-  [EIP145](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-145.md) In progress
  - https://github.com/ethereum/py-evm/pull/1112 (merged)
  - https://github.com/ethereum/py-evm/pull/1134 (under review)

**Comment by pipermerriam** [comment] 2018-08-01 17:06
Trinity: Here is the issue link for EIP1052

https://github.com/ethereum/py-evm/issues/719

**Comment by mkalinin** [comment] 2018-08-07 11:03
EthereumJ: https://github.com/ethereum/ethereumj/issues/1149

**Comment by cburgdorf** [comment] 2018-08-07 13:00
@Souptacular you can check EIP 145 for Trinity. It's implemented in https://github.com/ethereum/py-evm/pull/1134 and https://github.com/ethereum/py-evm/pull/1112 which are both merged in latest master

**Comment by Souptacular** [comment] 2018-08-08 19:38
Updated!

**Comment by holgerd77** [comment] 2018-08-09 08:52
Can we eventually add progress on the test cases written in https://github.com/ethereum/tests to the progress tracker, maybe with the number of implemented/merged test cases on the column for an EIP? @winsvega?

Have absolutely no overview on the current state there.

In this context I just rediscovered [this](https://docs.google.com/spreadsheets/d/1xat7UI8GtB4ZGVdlK5_XQSHJZaMThi4SrlcL8XMZb5Q/edit#gid=1811198384) test cases collection spreadsheet for Metropolis, is this still updated/cared for or is there an alternative collection like this existing?

**Comment by winsvega** [comment] 2018-08-09 09:30
yes. that google list is tracking new tests since before Metropolis. It is being updated.

**Comment by holgerd77** [comment] 2018-08-09 13:38
@winsvega Ah great, would be really good if you guys can keep the doc as up-to-date as possible and also make it clear which tests are implemented and where to find the implementation (like being done in the ``RETURN CODES`` sheet e.g.). This really helps us a lot on the implementation side!

**Comment by chfast** [comment] 2018-08-10 13:34
cpp-ethereum / EXTCODEHASH implemented.

**Comment by cburgdorf** [comment] 2018-08-17 08:59
We implemented `CREATE2` in Trinity. I will add that in contrast to the other new opcodes though, this one hasn't received much testing yet

https://github.com/ethereum/py-evm/pull/1186

**Comment by zilm13** [comment] 2018-08-24 08:13
EthereumJ/Harmony:
EIP 145: Bitwise shifting instructions in EVM implemented
EIP 1052: EXTCODEHASH Opcode implemented
everything else in progress

**Comment by chfast** [comment] 2018-08-31 13:48
Aleth / EIP 1283 done: https://github.com/ethereum/aleth/pull/5231

**Comment by lrettig** [comment] 2018-09-06 12:08
Added EIP-1234 to the tracker

**Comment by flygoing** [comment] 2018-09-07 13:12
Can the links to 145/1014 be updated to point to their respective eips.ethereum.org page? 1014 points to the pull request, which makes it difficult for people unfamiliar with git to read it.

**Comment by 5chdn** [comment] 2018-09-08 13:07
Parity Ethereum merged EIP-1283 https://github.com/paritytech/parity-ethereum/pull/9319

Parity Ethereum PR for EIP-1234 is https://github.com/paritytech/parity-ethereum/pull/9480 now

**Comment by ayrat555** [comment] 2018-09-11 17:10
Mana implemented EIP-145  https://github.com/poanetwork/mana/pull/417

**Comment by eosclassicteam** [comment] 2018-09-12 13:11
geth EIP-1234 in progress https://github.com/ethereum/go-ethereum/pull/17657

@5chdn

**Comment by ayrat555** [comment] 2018-09-12 13:56
Mana EIP-1052 done https://github.com/poanetwork/mana/pull/420

**Comment by Souptacular** [comment] 2018-09-12 21:06
@flygoing Done!

Chart updated.

**Comment by ytrezq** [comment] 2018-09-12 21:45
@Souptacular : what about [EIP86](https://github.com/ethereum/EIPs/issues/86) which was planned for Metropolis ?

**Comment by eosclassicteam** [comment] 2018-09-13 07:27
@Souptacular I think the link is broken for geth - EIP 1283

It should be https://github.com/ethereum/go-ethereum/pull/17383

**Comment by mkalinin** [comment] 2018-09-14 13:15
EthereumJ EIP-1283 PR merged, https://github.com/ethereum/ethereumj/pull/1173

**Comment by tkstanczak** [comment] 2018-09-18 10:29
EIP-1052 is done and tested in Nethermind

**Comment by tkstanczak** [comment] 2018-09-18 10:32
Nethermidn meta here: https://github.com/tkstanczak/nethermind/issues/93

**Comment by ayrat555** [comment] 2018-09-18 15:19
Mana / EIP-1014  https://github.com/poanetwork/mana/pull/426

**Comment by tkstanczak** [comment] 2018-09-18 16:11
Nethermind EIP-1014 done

**Comment by tkstanczak** [comment] 2018-09-18 16:11
Nethermind EIP-1234 done

**Comment by tkstanczak** [comment] 2018-09-18 18:12
Nethermind EIP-1283 done

**Comment by tkstanczak** [comment] 2018-09-18 18:13
Nethermind all done, I will run available blockchain tests from ethereum/tests tomorrow to see if everything is fine.

**Comment by tkstanczak** [comment] 2018-09-19 11:46
Do we expect an ethereum/test branch for Constantinople? Noticed that develop branch has incorrect mix hashes, block rewards and stExtCodeHash tests missing. Does anyone have an info on the golden source of tests for Constantinople?

**Comment by winsvega** [comment] 2018-09-19 12:07
incorrect mixhashes are due to this change: 
https://github.com/ethereum/tests/issues/480

stExtCodeHash are not ready. 
The Constantinople tests are marked by Constantinople section in tests itself. no need to create separate branch.

**Comment by ayrat555** [comment] 2018-09-20 18:16
Mana / EIP-1283 done  https://github.com/poanetwork/mana/pull/433

**Comment by karalabe** [comment] 2018-09-21 11:17
Net sstore also merged on Geth https://github.com/ethereum/go-ethereum/pull/17383 . We were waiting with this for a release, but postponed v1.8.16 for next Monday, so figured we can push it out now.

**Comment by cburgdorf** [comment] 2018-09-22 13:31
@Souptacular EIP 1234 just landed in Trinity https://github.com/ethereum/py-evm/pull/1303

**Comment by ayrat555** [comment] 2018-09-26 10:15
EIP 1234 is merged in Mana https://github.com/poanetwork/mana/pull/447

**Comment by mkalinin** [comment] 2018-10-05 09:09
EthereumJ. CREATE2 gas price update merged https://github.com/ethereum/ethereumj/pull/1204

**Comment by 5chdn** [comment] 2018-10-08 12:16
Parity is ready to hardfork Ropsten w/ updated CREATE2 spec.

- https://github.com/paritytech/parity-ethereum/pull/9562
- https://github.com/paritytech/parity-ethereum/pull/9688
- https://github.com/paritytech/parity-ethereum/pull/9694
- https://github.com/paritytech/parity-ethereum/pull/9704

**Comment by ajsutton** [comment] 2018-10-11 00:19
I'm happy to add that Pantheon has added support for all the Constantinople EIPs, including the updated CREATE2 spec.

**Comment by holgerd77** [comment] 2018-10-11 12:22
EthereumJS:
CREATE2 (EIP-1014):
Unknown -> WIP (https://github.com/ethereumjs/ethereumjs-vm/pull/329)
SSTORE (EIP-1283):
Unknown -> now merged, ready (https://github.com/ethereumjs/ethereumjs-vm/pull/367)
Difficulty Bomb (EIP-1234):
Unknown -> WIP (https://github.com/ethereumjs/ethereumjs-block/pull/54)

**Comment by cburgdorf** [comment] 2018-10-22 23:19
@Souptacular trinity just landed support for EIP-1283 https://github.com/ethereum/py-evm/pull/1410
Only thing left for us is to ensure we run all state tests for constantinople (which should land within the next days)

**Comment by dwightguth** [comment] 2018-10-31 16:46
KEVM now supports constantinople: https://github.com/kframework/evm-semantics/pull/267

We will continue to test with more up-to-date versions of the test suite up until launch.

**Comment by ehildenb** [comment] 2018-11-01 11:33
@Souptacular can you add us to the client matrix in the first comment?

**Comment by shemnon** [comment] 2018-11-01 15:03
Pantheon's github repo is now open and can be linked: https://github.com/PegaSysEng/pantheon

**Comment by InoMurko** [comment] 2018-11-04 16:48
Since joined forces have been announced to work on Mana, exthereum should be removed.

**Comment by holgerd77** [comment] 2018-11-06 23:07
EthereumJS: CREATE2 (EIP-1014), Difficulty bomb (EIP-1234): WIP -> Complete

**Comment by holgerd77** [comment] 2018-11-06 23:09
Associated PRs:
CREATE2: https://github.com/ethereumjs/ethereumjs-vm/pull/329
Difficulty bomb: https://github.com/ethereumjs/ethereumjs-block/pull/54

**Comment by winsvega** [comment] 2018-11-14 23:52
Could we extend the head post with following links to the test cases lists? 
this links also contain links to the actual tests in the repo. 

1) extcodehash cases: https://docs.google.com/spreadsheets/d/1xat7UI8GtB4ZGVdlK5_XQSHJZaMThi4SrlcL8XMZb5Q/edit?pli=1#gid=1811198384

2) bitshift cases: 
https://docs.google.com/spreadsheets/d/1xat7UI8GtB4ZGVdlK5_XQSHJZaMThi4SrlcL8XMZb5Q/edit?pli=1#gid=2010405893

3) sstore cases:
https://docs.google.com/spreadsheets/d/1xat7UI8GtB4ZGVdlK5_XQSHJZaMThi4SrlcL8XMZb5Q/edit?pli=1#gid=878289780

4) create2 cases;
https://docs.google.com/spreadsheets/d/1xat7UI8GtB4ZGVdlK5_XQSHJZaMThi4SrlcL8XMZb5Q/edit?pli=1#gid=1872446916

5) difficulty change and reward change related:
https://docs.google.com/spreadsheets/d/1xat7UI8GtB4ZGVdlK5_XQSHJZaMThi4SrlcL8XMZb5Q/edit?pli=1#gid=1197466216

**Comment by 5chdn** [comment] 2018-11-15 09:34
Might make sense to put this in the wiki, so everyone can edit it. Maybe directly here in the repository? Need a hand @lrettig @Souptacular ?

**Comment by holgerd77** [comment] 2018-11-15 12:18
@5chdn This is the main working sheet for @winsvega to organize test creation, I think the wiki here wouldn't be the right place for this, let's please just stick to linking this as originally suggested.

**Comment by 5chdn** [comment] 2018-11-15 15:59
Yeah, I'm just talking about "extending the head" post, it would be easier to have the ability to just edit a wiki somewhere instead of waiting for one person to do it. I'm not talking about adding the content of the links to the wiki.

**Comment by lrettig** [comment] 2018-11-18 22:17
I migrated the progress tracker to a wiki page at https://github.com/ethereum/pm/wiki/Constantinople-Progress-Tracker but it looks like it may still not have global edit access. @Souptacular will have to fix that.

**Comment by Souptacular** [comment] 2018-11-19 23:57
@lrettig I set up the proper permissions now.

**Comment by 5chdn** [comment] 2018-11-20 12:05
Amazing. Updated!

**Comment by sea51930** [comment] 2018-12-03 18:40
Duplicate of #

**Comment by sea51930** [comment] 2018-12-03 18:40
#63

**Comment by 5chdn** [comment] 2018-12-09 08:48
Moving the meta-EIP 1013 to final https://github.com/ethereum/EIPs/pull/1642

I think this tracker can be closed now.

**Comment by lrettig** [comment] 2018-12-12 08:16
Closing

**Closed by lrettig** 2018-12-12 08:16 UTC
